[package]
name = "warbot"
version = "0.1.0"
authors = ["Wraithan (Chris McDonald) <xwraithanx@gmail.com>"]
build = "build.rs"
include = ["src/**/*", "Cargo.toml", "tests/**/*"]

[build-dependencies]
glob = "*"