[package]
name = "warlib"
version = "0.1.0"
authors = ["Wraithan (Chris McDonald) <xwraithanx@gmail.com>"]
build = "build.rs"

[dependencies]
log = "*"
rand = "*"

[dev-dependencies]
env_logger = "*"

[build-dependencies]
glob = "*"
